# Generated by Django 3.2.9 on 2021-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blog_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='populer',
            field=models.BooleanField(default=True),
        ),
    ]
