# Generated by Django 3.2.9 on 2021-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_populer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='populer',
            field=models.BooleanField(default=False),
        ),
    ]
