# Generated by Django 3.2.9 on 2021-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blog_populer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='E-Mail')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
    ]
