# Generated by Django 3.2.9 on 2021-12-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
