# Generated by Django 3.2.9 on 2021-12-16 12:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0011_auto_20211216_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Blog Yazarı:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=ckeditor.fields.RichTextField(verbose_name='Blog İçeriği:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.FileField(upload_to='images/', verbose_name='Kapak Fotoğrafı:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Blog Başlığı:'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='populer',
            field=models.BooleanField(default=False, verbose_name='Popüler?'),
        ),
    ]
